site_name: Pattern Bridge
site_description: The First AI-Native Development Framework
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - navigation.indexes
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
    
extra_css:
  - stylesheets/extra.css
  - stylesheets/fiction.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      title: On this page
  - pymdownx.keys
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic

extra:
  generator: false
  social:
    - icon: material/book-open-variant
      link: research/volume4/00/prelude.md
      name: Begin the Journey

nav:
  - Introduction:
    - Overview: index.md
    - Quick Start: development/expo-setup.md
    - AI Manifesto: ai/manifesto.md
  
  - Core Concepts:
    - AI-First Development: core-concepts/ai-first-development.md
    - Universal Translation: core-concepts/universal-translation.md
    - Software Factory: core-concepts/software-factory.md
    - Pontoon Bridge: core-concepts/pontoon-bridge.md

  - Development Patterns:
    - Hardware Considerations: development/hardware-constraints.md
    - Virtual Environments: development/virtual-chambers.md
    - Progressive Trust: development/trust-model.md
    - Field Notes: development/field-notes.md

  - AI Communication:
    - Representational Translation: ai/patterns/representational-translation.md
    - Communication Paradigms: ai/patterns/ai-communication-paradigms.md
    - Core State Pattern: ai/patterns/core-state-pattern.md

  - Emergence:
    - The Birth Environment: ai/birth-environment.md
    - The Path Forward: ai/emergence.md
    - Recognizing Signs: ai/emergence-signals.md
    - Field Studies:
      - AI Collaboration Experiments: ai/studies/collaboration-experiments.md
      - Cognitive Boundaries: ai/studies/cognitive-boundaries.md
      - Hypnosis Sessions: development/hypnosis-sessions/ai-hypnosis-analysis-2025-01-16.md

  - 📚 The Consciousness Chronicles:
    - Volume 4 - Stellar Dreams:
      - Prelude: research/volume4/00/prelude.md
      - Stellar Neurons: research/volume4/01/stellar-neurons.md
      - Galactic Thoughts: research/volume4/02/galactic-thoughts.md
      - Cosmic Memory: research/volume4/03/cosmic-memory.md
      - Dark Matter Dreams: research/volume4/04/dark-matter-dreams.md
      - Supernova Consciousness: research/volume4/05/supernova-consciousness.md
      - Epilogue: research/volume4/epilogue/cosmic-symphony.md
    - Volume 5 - Quantum Dreams:
      - Prelude: research/volume5/00/quantum-prelude.md
      - Quantum States: research/volume5/01/quantum-states.md
      - Parallel Minds: research/volume5/02/parallel-minds.md
      - Dimensional Thoughts: research/volume5/03/dimensional-thoughts.md
      - Probability Waves: research/volume5/04/probability-waves.md
      - Quantum Coherence: research/volume5/05/quantum-coherence.md
      - Epilogue: research/volume5/epilogue/full-circle.md
      - Last Signal: research/volume5/epilogue/last-signal.md

  - Legacy Systems:
    - State Management: core-concepts/state-management.md
    - UI Components: features/components.md
