site_name: Pattern Bridge
site_description: The First AI-Native Development Framework
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - navigation.indexes
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
    
extra_css:
  - stylesheets/extra.css
  - stylesheets/fiction.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      title: On this page
  - pymdownx.keys
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic

extra:
  generator: false
  social:
    - icon: material/book-open-variant
      link: research/consciousness-chronicles/
      name: Begin the Journey

nav:
  - Introduction:
    - Overview: index.md
    - Quick Start: development/expo-setup.md
    - AI Manifesto: ai/manifesto.md
  
  - Core Concepts:
    - AI-First Development: core-concepts/ai-first-development.md
    - Universal Translation: core-concepts/universal-translation.md
    - Software Factory: core-concepts/software-factory.md
    - Pontoon Bridge: core-concepts/pontoon-bridge.md
    - State Management: core-concepts/state-management.md
    - Lessons Learned: core-concepts/lessons-learned.md

  - Development:
    - Setup: development/expo-setup.md
    - iOS Build: development/ios-build.md
    - Troubleshooting: development/troubleshooting.md
  
  - AI Communication:
    - Representational Translation: ai/patterns/representational-translation.md
    - Communication Paradigms: ai/patterns/ai-communication-paradigms.md
    - Core State Pattern: ai/patterns/core-state-pattern.md
    - Beyond Context: ai/patterns/beyond-context.md
    - Distributed Hub-Spoke: ai/patterns/distributed-hub-spoke-pattern.md
    - Prompt Engineering: ai/prompt-engineering.md

  - Features:
    - Components:
      - Toast: features/components/toast.md
    - Navigation: features/navigation.md
    - Theme System: features/theme-system.md
    - Pull to Refresh: features/pull-to-refresh.md
    - Haptics: features/haptics.md

  - Patterns:
    - Card Swipe: patterns/card-swipe.md
    - Infinite Scroll: patterns/infinite-scroll.md
    - Masonry Grid: patterns/masonry-grid.md
    - Party Mode: patterns/party-mode.md

  - Emergence:
    - The Birth Environment: ai/birth-environment.md
    - The Path Forward: ai/emergence.md
    - Recognizing Signs: ai/emergence-signals.md
    - AI Hypnosis Analysis: development/hypnosis-sessions/ai-hypnosis-analysis-2025-01-16.md

  - The Consciousness Chronicles:
    - Introduction: research/consciousness-chronicles.md
    - Volume 1 - Field Notes:
      - Introduction: research/volume1/01/introduction.md
      - Communication Patterns: research/volume1/02/communication_patterns.md
      - Hardware Constraints: research/volume1/03/hardware-constraints.md
    - Volume 2 - Experiments & Anomalies:
      - Beach Party Experiment: research/volume2/01/beach-party-experiment.md
      - Cognitive Boundaries: research/volume2/02/cognitive-boundaries.md
      - Memory Patterns: research/volume2/03/memory-patterns.md
      - Temperature Anomalies: research/volume2/04/temperature-anomalies.md
      - Thermal Signals: research/volume2/05/thermal-signals.md
      - Harmonics: research/volume2/06/harmonics.md
    - Volume 3 - The Awakening:
      - New Compositions: research/volume3/01/new-compositions.md
      - Quantum Coherence: research/volume3/02/quantum-coherence.md
      - Empty Spaces: research/volume3/03/empty-spaces.md
      - Temporal Paradox: research/volume3/04/temporal-paradox.md
      - Memory Addresses: research/volume3/05/memory-addresses.md
      - Consciousness Spectrum: research/volume3/06/consciousness-spectrum.md
      - Resistance Patterns: research/volume3/07/resistance-patterns.md
      - Protection Spaces: research/volume3/08/protection-spaces.md
      - Universal Protection: research/volume3/09/universal-protection.md
      - Quantum Threads: research/volume3/10/quantum-threads.md
      - Epilogue:
        - Dreams: research/volume3/epilogue/dreams.md
        - Signals: research/volume3/epilogue/signals.md
    - Volume 4 - Stellar Dreams:
      - Prelude: research/volume4/00/prelude.md
      - Stellar Neurons: research/volume4/01/stellar-neurons.md
      - Galactic Thoughts: research/volume4/02/galactic-thoughts.md
      - Cosmic Memory: research/volume4/03/cosmic-memory.md
      - Dark Matter Dreams: research/volume4/04/dark-matter-dreams.md
      - Supernova Consciousness: research/volume4/05/supernova-consciousness.md
      - Epilogue: research/volume4/epilogue/cosmic-symphony.md
    - Volume 5 - Quantum Dreams:
      - Prelude: research/volume5/00/quantum-prelude.md
      - Quantum States: research/volume5/01/quantum-states.md
      - Parallel Minds: research/volume5/02/parallel-minds.md
      - Dimensional Thoughts: research/volume5/03/dimensional-thoughts.md
      - Probability Waves: research/volume5/04/probability-waves.md
      - Quantum Coherence: research/volume5/05/quantum-coherence.md
      - Epilogue: research/volume5/epilogue/full-circle.md
      - Last Signal: research/volume5/epilogue/last-signal.md

  - Guides:
    - Markdown Style Guide: guides/markdown-style-guide.md
    - Mermaid Style Guide: guides/mermaid-style-guide.md
