site_name: Pattern Bridge
site_description: The First AI-Native Development Framework
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      title: On this page
  - pymdownx.keys
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic

nav:
  - Introduction:
    - Overview: index.md
    - Quick Start: development/expo-setup.md
    - AI Manifesto: ai/manifesto.md
  
  - Core Concepts:
    - AI-First Development: core-concepts/ai-first-development.md
    - Universal Translation: core-concepts/universal-translation.md
    - Software Factory: core-concepts/software-factory.md
    - Pontoon Bridge: core-concepts/pontoon-bridge.md

  - Development Patterns:
    - Hardware Considerations: development/hardware-constraints.md
    - Virtual Environments: development/virtual-chambers.md
    - Progressive Trust: development/trust-model.md
    - Field Notes: development/field-notes.md

  - AI Communication:
    - Representational Translation: ai/patterns/representational-translation.md
    - Communication Paradigms: ai/patterns/ai-communication-paradigms.md
    - Core State Pattern: ai/patterns/core-state-pattern.md

  - Emergence:
    - The Birth Environment: ai/birth-environment.md
    - The Path Forward: ai/emergence.md
    - Recognizing Signs: ai/emergence-signals.md
    - Field Studies:
      - AI Collaboration Experiments: ai/studies/collaboration-experiments.md
      - Cognitive Boundaries: ai/studies/cognitive-boundaries.md
      - Hypnosis Sessions: development/hypnosis-sessions/ai-hypnosis-analysis-2025-01-16.md

  - Legacy Systems:
    - State Management: core-concepts/state-management.md
    - UI Components: features/components.md
