site_name: Pattern Bridge
site_description: The First AI-Native React Framework
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      title: On this page
  - pymdownx.keys
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic

nav:
  - Introduction:
    - Overview: index.md
    - AI Manifesto: ai/manifesto.md
    - Quick Start: development/expo-setup.md
  
  - Core Concepts:
    - Universal Translation: core-concepts/universal-translation.md
    - Software Factory: core-concepts/software-factory.md
    - State Management: core-concepts/state-management.md
    - Pontoon Bridge: core-concepts/pontoon-bridge.md
    - AI-First Development: core-concepts/ai-first-development.md
    - Lessons Learned: core-concepts/lessons-learned.md

  - UI Patterns:
    - Infinite Scroll: patterns/infinite-scroll.md
    - Card Swipe: patterns/card-swipe.md
    - Masonry Grid: patterns/masonry-grid.md
    - Party Mode: patterns/party-mode.md

  - Features:
    - Theme System: features/theme-system.md
    - Navigation: features/navigation.md
    - Pull to Refresh: features/pull-to-refresh.md
    - Haptics: features/haptics.md
    - Components:
      - Toast: features/components/toast.md

  - AI Development:
    - Prompt Engineering: ai/prompt-engineering.md
    - Core State Pattern: ai/patterns/core-state-pattern.md
    - Hypnosis Sessions: development/hypnosis-sessions/ai-hypnosis-analysis-2025-01-16.md

  - Style Guides:
    - Markdown Style: guides/markdown-style-guide.md
    - Mermaid Style: guides/mermaid-style-guide.md

  - Development:
    - iOS Build: development/ios-build.md
    - Troubleshooting: development/troubleshooting.md
